### ISSUE TITLE
[feature] 关于剪贴板快递柜的建议

### ISSUE THREAD

**Issue by MurphyLo** [LeafYeeXYZ/FileBox#2]
很多时候尤其是在配置新设备时，需要在手机或电脑之间传递长字符串（如秘钥、网址等文本信息），使用文件快递柜进行传输就显得不那么方便了。佬是否可以开发一个剪贴板快递柜作为附加功能，仅用于转储字符串 ♪(･ω･)ﾉ

**Comment by LeafYeeXYZ** [comment]
好呀!

#### TODO

- [x] 元数据存储内容新增 `type: 'file' | 'text'` 项
- [x] 修改上传下载后端逻辑
- [x] 修改上传下载前端界面

**Comment by LeafYeeXYZ** [comment]
完成啦!
